export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_LOGIN_COMPLETE = 'AUTH_LOGIN_COMPLETE';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_REGISTER_START = 'AUTH_REGISTER_START';
export const AUTH_REGISTER_COMPLETE = 'AUTH_REGISTER_COMPLETE';
export const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';
