export const APP_PAGE_LOADER_SHOW = 'APP_PAGE_LOADER_SHOW';
export const APP_PAGE_LOADER_HIDE = 'APP_PAGE_LOADER_HIDE';
export const APP_PAGE_LOADER_ATTACH_TO_DOM = 'APP_PAGE_LOADER_ATTACH_TO_DOM';
export const APP_PAGE_LOADER_DETACH_FROM_DOM = 'APP_PAGE_LOADER_DETACH_FROM_DOM';
